{
    "openapi": "3.0.0",
    "info": {
        "title": "SEE Automatic Documentation Generator",
        "description": "Project to develop an API to register Athlete Sponsorship Projects and automatically generate documentation from the Special Secretariat for Sports of the municipality of Ipojuca",
        "version": "1.0.0",
        "contact": {
            "email": "marceloraposo.dev@gmail.com"
        }
    },
    "servers": [
        {
            "url": "http://localhost:3333",
            "description": "Test API"
        }
    ],
    "paths":{
        "/address/": {
            "post": {
                "tags": ["Address"],
                "summary": "Create Address",
                "description": "It should be possible to register an Address.",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "example": {
                                "street": "Rua de teste",
                                "number": 100,
                                "city": "Cidade de teste",
                                "state": "Pernambuco",
                                "cep": "55590000"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Address created!"
                    }
                }
            },
            "get": {
                "tags": ["Address"],
                "summary": "List Addresses",
                "description": "It should be possible to list all registered addresses.",
                "responses": {
                    "200": {
                        "description": "Ok"
                    }
                }
            }
        },
        "/address/{id}": {
            "get": {
                "tags": ["Address"],
                "summary": "Find Address by ID",
                "description": "It should be able to find an address by ID",
                "security": [{ "bearerAuth": [] }],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Address ID",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Address"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Address do not exists!"
                    }
                }
            },
            "put": {
                "tags": ["Address"],
                "summary": "Update Address",
                "description": "It should be possible to update a registered address.",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Address ID",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "example": {
                                "street": "Rua Teste Updated",
                                "number": 999,
                                "city": "Cidade Teste Updated",
                                "state": "Estado Teste Updated",
                                "cep": "55590000 Updated"
                            }        
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Updated Address!"
                    },
                    "400": {
                        "description": "Address do not exists!"
                    }
                }
            },
            "delete": {
                "tags": ["Address"],
                "summary": "Delete Address",
                "description": "It should be possible to delete an address.",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Address ID",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deleted address!"
                    },
                    "400": {
                        "description": "Address do not exists!"
                    }
                }
            }
        },
        "/athleteResponsible/": {
            "post": {
                "tags": ["Athlete Responsible"],
                "summary": "Create Athlete Responsible",
                "description": "It should be possible to register an Athlete Responsible.",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "example": {
                                "name": "Nome do Responsável",
                                "cpf": "11122233344", 
                                "rg": "1222333-SDS", 
                                "email": "responsavel@email.com", 
                                "phoneNumber": "81977774444", 
                                "profession": "Profissão do Responsável", 
                                "maritalStatus": "Estado civil do Responsável",
                                "addressId": "af3e90d3-6ae2-4a79-b402-bc207861dc97"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/AthleteResponsible"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Athlete Responsible already exists!"
                    }
                }
            }
        }    
    },
    "components": {
        "schemas": {
            "Address": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "street": {
                        "type": "string"
                    },
                    "number": {
                        "type": "number"
                    },
                    "city": {
                        "type": "string"
                    },
                    "state": {
                        "type": "string"
                    },
                    "cep": {
                        "type": "string"
                    },
                    "created_at": {
                        "type": "datetime"
                    },
                    "update_at": {
                        "type": "datetime"
                    }
                }
            },
            "AthleteResponsible": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "cpf": {
                        "type": "number"
                    },
                    "rg": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "phoneNumber": {
                        "type": "string"
                    },
                    "profession": {
                        "type": "string"
                    },
                    "maritalStatus": {
                        "type": "string"
                    },
                    "addressId": {
                        "type": "string"
                    },
                    "created_at": {
                        "type": "datetime"
                    },
                    "update_at": {
                        "type": "datetime"
                    }
                }
            }
        }
    }
}